services:
  - type: web
    name: cloud-todo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-todo-db
          property: connectionString

databases:
  - name: cloud-todo-db
    plan: free
